#!/bin/bash

#Script to make data file compatible to gnuplot gif plotting
#It will divide file such that first frame of gif will have first 100 points, next frame first 200 and so on

rm pi_1.txt

for ((j=100;i<10000;j+=100)); do 
for ((i=1;i<j+1;i+=1));  do grep "" ./pi.dat | awk -v i="$i" '{if(NR==i) print}' >> pi_1.txt;   done ; echo >> pi_1.txt ; echo >> pi_1.txt ; done

gnuplot pi_gif.p

